development:
  easy_broken_host:  <%= ENV["EASY_BROKEN_HOST"] %>
  easy_broken_api_key: <%= ENV["EASY_BROKEN_API_KEY"] %>
test:
  easy_broken_host:  'http://localhost'
  easy_broken_api_key: 'mepmep'
staging:
  easy_broken_host:  <%= ENV["EASY_BROKEN_HOST"] %>
  easy_broken_api_key: <%= ENV["EASY_BROKEN_API_KEY"] %>
production:
  easy_broken_host:  <%= ENV["EASY_BROKEN_HOST"] %>
  easy_broken_api_key: <%= ENV["EASY_BROKEN_API_KEY"] %>